### ISSUE TITLE
How can I setup/install this project?

### ISSUE THREAD

**Issue by radelphe** [BeeBombshell/Queuelio#1]
Are there any instructions on how to setup this project?

**Comment by BeeBombshell** [comment]
Hi @radelphe, if you have npm or yarn installed, you can simply install the dependencies using the following command:

`npm install` for npm 
or
`yarn` for yarn

And run:
`npm start`
or 
`yarn run`

Hope your doubt will be resolved! 😄

**Comment by radelphe** [comment]
Thanks @BeeBombshell  for you quick response. I did run npm start and the app is running but I can’t get a user registered. I’m blocked with OTP. Any help?

**Comment by radelphe** [comment]
I think I figured it out with https://github.com/GauravDubey56/FLask_OTP_API
